//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Zaposlenik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI2220_DBEntities : DbContext
    {
        public PI2220_DBEntities()
            : base("name=PI2220_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikl> Artikls { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Narudzba> Narudzbas { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<stavka_narudzbe> stavka_narudzbe { get; set; }
        public virtual DbSet<Stol> Stols { get; set; }
        public virtual DbSet<Uloga> Ulogas { get; set; }
        public virtual DbSet<Vrsta_artikla> Vrsta_artiklas { get; set; }
        public virtual DbSet<Status_narudzbe> Status_narudzbes { get; set; }
        public virtual DbSet<Raspored> Rasporeds { get; set; }
        public virtual DbSet<TipSmjene> TipSmjenes { get; set; }
        public virtual DbSet<Rezervacija> Rezervacijas { get; set; }
    }
}
