//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Zaposlenik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int id_racun { get; set; }
        public int id_korisnik { get; set; }
        public int id_narudzba { get; set; }
        public System.DateTime datum_i_vrijeme { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Narudzba Narudzba { get; set; }
    }
}
