//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Zaposlenik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int id_rezervacije { get; set; }
        public string email_gosta { get; set; }
        public string tel_gosta { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datum_rezervacije { get; set; }
        public byte odobrena { get; set; }
        public int id_dodao { get; set; }
        public int id_odobrio { get; set; }
        public System.DateTime datum_dogadaja { get; set; }
        public string opis_dogadaja { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
    }
}
