//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Zaposlenik
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipSmjene
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipSmjene()
        {
            this.Rasporeds = new HashSet<Raspored>();
        }
    
        public int id_tip_smjene { get; set; }
        public string tip_smjene { get; set; }
        public System.TimeSpan vrijeme_pocetka { get; set; }
        public System.TimeSpan vrijeme_kraja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raspored> Rasporeds { get; set; }
    }
}
