//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Gost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikl()
        {
            this.stavka_narudzbe = new HashSet<stavka_narudzbe>();
        }
    
        public int id_artikl { get; set; }
        public string naziv_artikla { get; set; }
        public double cijena { get; set; }
        public int kolicina_u_skladistu { get; set; }
        public double kolicina_u_litrama { get; set; }
        public int id_vrste_artikla { get; set; }
    
        public virtual Vrsta_artikla Vrsta_artikla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavka_narudzbe> stavka_narudzbe { get; set; }
    }
}
